name: Build & Release

on:
  push:
    tags: [ 'v*' ]   # v로 시작하는 태그 푸시될 때 실행됨

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make plugin zip (wrap in folder)
        run: |
          PLUG=berry-lean
          mkdir -p build/$PLUG
          shopt -s extglob
          cp -R !(build|.git|.github) build/$PLUG
          cd build && zip -r ${PLUG}.zip $PLUG

      - name: Attach zip to Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/berry-lean.zip
